# Generated by Django 4.0.4 on 2022-05-29 22:58

import app_maps.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id_County', models.AutoField(primary_key=True, serialize=False)),
                ('cod_ibge', models.IntegerField(blank=True, null=True)),
                ('name_county', models.CharField(blank=True, max_length=254, null=True)),
                ('initials_uf', models.CharField(blank=True, max_length=250, null=True)),
                ('name_ugrhi', models.CharField(blank=True, max_length=254, null=True)),
                ('number_ugrhi', models.IntegerField(blank=True, null=True)),
                ('cod_environmental', models.IntegerField(blank=True, null=True)),
                ('area_county', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Equipament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=80)),
                ('viewValue', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='GeoDadosEspaciais',
            fields=[
                ('id_espatial', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to=app_maps.models.upload_file_espatial)),
                ('fileupload', models.FileField(blank=True, null=True, upload_to=app_maps.models.upload_file_espatial)),
                ('file_dbf', models.FileField(blank=True, null=True, upload_to=app_maps.models.upload_file_espatial)),
                ('file_prj', models.FileField(blank=True, null=True, upload_to=app_maps.models.upload_file_espatial)),
                ('file_qpj', models.FileField(blank=True, null=True, upload_to=app_maps.models.upload_file_espatial)),
                ('file_cpg', models.FileField(blank=True, null=True, upload_to=app_maps.models.upload_file_espatial)),
                ('file_shp', models.FileField(blank=True, null=True, upload_to=app_maps.models.upload_file_espatial)),
                ('file_shx', models.FileField(blank=True, null=True, upload_to=app_maps.models.upload_file_espatial)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeInfraestructure', models.CharField(max_length=80)),
                ('idDetentor', models.IntegerField()),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('id_layer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id_state', models.AutoField(primary_key=True, serialize=False)),
                ('name_state', models.CharField(blank=True, max_length=254, null=True)),
                ('cod_uf', models.CharField(blank=True, max_length=250, null=True)),
                ('initials_uf', models.CharField(blank=True, max_length=250, null=True)),
                ('nome_region', models.CharField(blank=True, max_length=250, null=True)),
                ('area_state', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TestGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id_district', models.AutoField(primary_key=True, serialize=False)),
                ('nome_district', models.CharField(blank=True, max_length=254, null=True)),
                ('area_district', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('id_County', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_maps.county')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='id_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_maps.state'),
        ),
    ]
