# Generated by Django 4.0.4 on 2022-06-14 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='co_unit_federal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_maps.federativeunit'),
        ),
    ]
