# Generated by Django 4.0.4 on 2022-06-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='co_cod_ibge',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
