# Generated by Django 4.0.4 on 2022-05-16 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=80)),
                ('viewValue', models.CharField(max_length=80)),
            ],
        ),
    ]
