# Generated by Django 4.0.4 on 2022-06-18 21:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0002_alter_county_co_unit_federal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplace',
            name='geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
