# Generated by Django 4.0.4 on 2022-05-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0002_alter_municipio_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nome_estado', models.CharField(blank=True, max_length=254, null=True)),
                ('sigla_uf', models.CharField(blank=True, max_length=250, null=True)),
                ('area_municipio', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_maps.estado'),
        ),
    ]
