# Generated by Django 4.0.4 on 2022-05-17 02:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0002_equipament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomeInfraestructure', models.CharField(max_length=80)),
                ('idDetentor', models.IntegerField()),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
