# Generated by Django 4.0.4 on 2022-05-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0003_infrastructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infrastructure',
            options={'managed': False},
        ),
    ]
