# Generated by Django 4.0.4 on 2022-06-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0003_geodadosespaciais_category_geodadosespaciais_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='federativeunit',
            name='uf_geocode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
