# Generated by Django 4.0.4 on 2022-05-24 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0003_estado_municipio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='codigo_uf',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='nome_regiao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id_bairro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_bairro', models.CharField(blank=True, max_length=254, null=True)),
                ('area_municipio', models.FloatField(blank=True, null=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_maps.municipio')),
            ],
        ),
    ]
