# Generated by Django 4.0.4 on 2022-06-18 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0003_alter_publicplace_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentcounty',
            name='eq_co_public_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_maps.publicplace'),
        ),
    ]
