# Generated by Django 4.0.4 on 2022-06-20 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0004_federativeunit_uf_geocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='infra_street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_maps.street'),
        ),
    ]
