# Generated by Django 4.0.6 on 2022-07-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0008_alter_network_net_subsystems'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicplace',
            name='pp_name_seg_log',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='publicplace',
            name='pp_name_tip_log',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publicplace',
            name='pp_name_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
