# Generated by Django 4.0.6 on 2022-07-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0010_geodadosespaciais_file_sbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplace',
            name='pp_cod_sector',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
