# Generated by Django 4.0.6 on 2022-07-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0011_alter_publicplace_pp_cod_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplace',
            name='pp_cod_block',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='publicplace',
            name='pp_cod_face',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
