# Generated by Django 4.0.6 on 2022-07-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0012_alter_publicplace_pp_cod_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplace',
            name='pp_total_general',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='publicplace',
            name='pp_total_residences',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
