# Generated by Django 4.0.6 on 2022-07-28 13:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0013_alter_publicplace_pp_total_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
    ]
