# Generated by Django 4.0.6 on 2022-07-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0014_alter_street_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodadosespaciais',
            name='namefile',
            field=models.CharField(blank=True, default='shape_<django.db.models.fields.UUIDField>', max_length=50, null=True),
        ),
    ]
